# IF the pull request comes from a branch other than a release-please branch, this workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests. If passed successfully, will run the release-please job to update the changelog and updated the release number and create a pull request.
# IF the pull request comes from a release-please branch, it will skip the build and test jobs, a run the release-please job


name: Build, Test and Release

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]


jobs:
  test:
    if: ${{ github.event_name == "push" && startsWith(github.ref, 'refs/heads/release-please') || github.event_name == "pull_request" && !startsWith(github.ref, 'refs/heads/release-please') }}
    runs-on: ubuntu-latest
    env: 
      CONTENTFUL_SPACE: ${{secrets.CONTENTFUL_SPACE}}
      CONTENTFUL_ACCESS_TOKEN: ${{secrets.CONTENTFUL_ACCESS_TOKEN}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
    

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm test
  
  release-please:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action